- community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ brew_packages }}"

- name: download macitbetter
  ansible.builtin.get_url:
    url: https://macitbetter.com/BetterZip.zip
    dest: ~/Downloads

- name: Download latest
  ansible.builtin.get_url:
    url: https://www.titanium-software.fr/download/15/Maintenance.dmg
    dest: ~/Downloads

- name: Download AppCleaner
  ansible.builtin.get_url:
    url: https://freemacsoft.net/downloads/AppCleaner_3.6.8.zip
    dest: ~/Downloads

- name: Download coconutbattery
  ansible.builtin.get_url:
    url: https://coconut-flavour.com/downloads/coconutBattery_latest.zip
    dest: ~/Downloads

- name: Download keka
  ansible.builtin.get_url:
    url: https://github.com/aonez/Keka/releases/download/v1.4.5/Keka-1.4.5.dmg
    dest: ~/Downloads

- name: run hblock
  ansible.builtin.shell: hblock