- name: MacOS Tweaks
  ansible.builtin.shell: |
    defaults write com.apple.dock "autohide-time-modifier" -float "0.2"
    defaults write com.apple.dock "autohide-delay" -float "0"
    defaults write com.apple.dock "show-recents" -bool "false"
    defaults write com.apple.screencapture "location" -string "~/Pictures/Screenshots"
    defaults write NSGlobalDomain "AppleShowAllExtensions" -bool "true"
    defaults write com.apple.finder "ShowPathbar" -bool "true"
    defaults write com.apple.finder "_FXSortFoldersFirst" -bool "true"
    defaults write com.apple.finder "FinderSpawnTab" -bool "true"
    defaults write com.apple.finder "FXRemoveOldTrashItems" -bool "true"
    defaults write com.apple.finder "FXEnableExtensionChangeWarning" -bool "false"
    defaults write com.apple.universalaccess "showWindowTitlebarIcons" -bool "true"
    defaults write NSGlobalDomain "NSToolbarTitleViewRolloverDelay" -float "0"
    defaults write com.apple.ActivityMonitor "UpdatePeriod" -int "2"
- name: Kill MacOS dock
  ansible.builtin.shell: killall Dock

- name: Wait 5 seconds
  ansible.builtin.wait_for:
    timeout: 5

- name: Kill MacOS SystemUIServer
  ansible.builtin.shell: killall SystemUIServer

- name: Wait 5 seconds
  ansible.builtin.wait_for:
    timeout: 5

- name: Kill finder
  ansible.builtin.shell: killall Finder