- name: Faster dock autohide
  ansible.builtin.shell: defaults write "com.apple.dock" autohide-time-modifier -float 0.12
  ignore_errors: true

- name: Remove all application in dock
  ansible.builtin.shell: defaults write "com.apple.dock" "persistent-apps" -array
  ignore_errors: true

- name: Set dock to bottom
  ansible.builtin.shell: defaults write com.apple.dock "orientation" -string "bottom"

- name: Change screenshot location
  ansible.builtin.shell: defaults write com.apple.screencapture "location" -string "~/Pictures/Screenshot"

- name: Set screenshot image format to png
  ansible.builtin.shell: defaults write com.apple.screencapture "type" -string "png"

- name: Allow quit finder
  ansible.builtin.shell: defaults write com.apple.finder "QuitMenuItem" -bool "true"

- name: Show finder path
  ansible.builtin.shell: defaults write com.apple.finder "ShowPathbar" -bool "true"

- name: Show folders before files
  ansible.builtin.shell: defaults write com.apple.finder "_FXSortFoldersFirst" -bool "true"

- name: Empty bin after 30 days
  ansible.builtin.shell: defaults write com.apple.finder "FXRemoveOldTrashItems" -bool "true"

- name: Ignore changing file extention
  ansible.builtin.shell: defaults write com.apple.finder "FXEnableExtensionChangeWarning" -bool "false"

- name: Do not save docs in icloud
  ansible.builtin.shell: defaults write NSGlobalDomain "NSDocumentSaveNewDocumentsToCloud" -bool "false"

- name: Faster toolbar hover
  ansible.builtin.shell: defaults write NSGlobalDomain "NSToolbarTitleViewRolloverDelay" -float "0"

- name: Disable mouse acceleration
  ansible.builtin.shell: defaults write NSGlobalDomain com.apple.mouse.linear -bool "true"

- name: Disable large file autogather
  ansible.builtin.shell: defaults write com.apple.appleseed.FeedbackAssistant "Autogather" -bool "false"

- name: Decrease activity monitor speed
  ansible.builtin.shell: defaults write com.apple.ActivityMonitor "UpdatePeriod" -int "1"

- name: Faster key repeat rate
  ansible.builtin.shell: defaults write -g InitialKeyRepeat -int 10

- name: Kill MacOS dock
  ansible.builtin.shell: killall Dock

- name: Wait 5 seconds
  ansible.builtin.wait_for:
    timeout: 5

- name: Kill MacOS SystemUIServer
  ansible.builtin.shell: killall SystemUIServer

- name: Wait 5 seconds
  ansible.builtin.wait_for:
    timeout: 5

- name: Kill MacOS safari
  ansible.builtin.shell: killall Safari

- name: Wait 5 seconds
  ansible.builtin.wait_for:
    timeout: 5

- name: Kill finder
  ansible.builtin.shell: killall Finder